### ISSUE TITLE
无法hook

### ISSUE THREAD

**Issue by TreeGrow** [safeYYY/easyHook#4]
测试了一个无壳demo，悬浮窗无显示。自己写的xp插件是可以的。不知道哪里出了问题。资源包的和样品的都下载了，进行了测试。无返回。
packageName = "com.lccc.demo";
ClassName = "com.lccc.demo.MainActivity";
methodName = "update"
参数 String.class
无截图

**Comment by safeYYY** [comment]
你观察下日志吧，有可能是因为高版本的Android需要增加个什么sd卡读取权限。好久没维护了，也没时间维护了

**Comment by qwn3213** [comment]
我也遇到这个问题，你的无壳demo需要有读写sd卡权限，因为easyHook写了个配置文件

```
File sdcardDir = Environment.getExternalStorageDirectory(); 
String filePath = sdcardDir.getAbsolutePath() + "/hookResult.txt";
```
